version: 2

project_name: serve

before:
  hooks:
    - go mod tidy

builds:
  - id: serve
    main: ./cmd/serve
    binary: serve
    env:
      - CGO_ENABLED=0
    goos:   [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/marr-cloud/serve/internal/config.Version={{.Version}}

archives:
  - id: serve
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: [README.md, LICENSE*]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^chore:", "^ci:", "Merge pull request"]

release:
  draft: false
  prerelease: auto
